name: Daily Commit

on:
  schedule:
    - cron: '0 5 * * *'  # Todos los días a las 5:00 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Crear contenido único
        run: |
          echo "Último commit: $(date -u)" > daily_update.txt
          echo "Hash aleatorio: $RANDOM$RANDOM" >> daily_update.txt

      - name: Commit y Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_update.txt
          git commit -m "Commit diario: $(date -u)" || echo "Sin cambios para hacer commit"
          git push
